---
- hosts: local
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  environment:
    AZURE_STORAGE_ACCOUNT: "{{sunbird_private_storage_account_name}}"
    AZURE_STORAGE_KEY: "{{sunbird_private_storage_account_key}}"
    OCI_CLI_AUTH: instance_principal
  roles:
    - data-products-deploy

